import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/app/components/header";
import { Box } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Box>
      <Header></Header>
      {children}
    </Box>
  );
}
